name: The Globe Wanderer
favicon: null
layout_spectrum: 0.88157
typography_spectrum: 0.27108
title: The Globe Wanderer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1218'
    - '#f9f7f8'
    - '#515151'
    - '#a4a3ab'
    - '#8eea2d'
  brandStrength: 0.33657930279150605
  lightness: 0.49733557808212936
  saturation: 0.7996763421688229
  rhythmicContrast: 0.4602981444913894
purpose: []
